_target_: src.core.geo-estimation.tibhannover_geoestimator.TIBHannoverEstimator
tib_checkpoint: /home/yitec/WORK/tung/GeoEstimation/models/base_M/epoch=014-val_loss=18.4833.ckpt
tib_hparams: /home/yitec/WORK/tung/GeoEstimation/models/base_M/hparams.yaml
