_target_: src.core.candidate_generation.streetclip_country_generator.StreetClipCountryCandidateGenerator
map_grids:
  _target_: src.core.common.components.CountryGrid.CountryGrid
num_candidates: 10
model_name: "geolocal/StreetCLIP"

use_torch_compiled: False
