defaults:
  - _self_
  - candidate-generation: streetclip.yaml
  - geo-estimation: tibhannover.yaml
  - location-ranking: random.yaml
  - metadata-extractor: exif.yaml 
  - streetview-image-scraper: empty.yaml
img: assets/imgs/london.jpeg