defaults:
  - _self_
  - candidate-generation: streetclip.yaml
  - geo-estimation: country-to-coord.yaml
  - location-ranking: random.yaml
  - metadata-extractor: empty.yaml 
img: assets/imgs/london.jpeg